### ISSUE TITLE
TypeError when fetching commits (in Firefox)

### ISSUE THREAD

**Issue by pprkut** [NirmalScaria/le-git-graph#25]
I tested the firefox extension with a couple repos, and for some it works quite nice, for some others I get a TypeError:

```
TypeError: data.data.repository is null
```
in
```
fetchCommits.js:119:31
```

So far I could only reproduce this with some private repositories, so not sure what exactly triggers this :-/

**Comment by NirmalScaria** [comment]
This was never observed and I am not able to reproduce this.
Please add some steps to reproduce the error, or try to provide a reference repo where this error is happening. Still, looking at the error message, this has to be something wrong with the usage of API for fetching commits.

**Comment by pprkut** [comment]
I'm also getting the same error in chrome, so at least it's not browser specific. Chrome's console gives me:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'refs')
    at fetchCommitsPage (fetchCommits.js:119:52)
    at async fetchCommits (fetchCommits.js:142:9)
    at async HTMLAnchorElement.openCommitsTab (openCommitsTab.js:45:9)
```

So far I could reproduce it with every private repo I tried

**Comment by pprkut** [comment]
https://github.com/move-sysadmin/saltstack-formula-freeradius is a public repo that gives me a slightly similar error:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'edges')
    at fetchCommitsPage (fetchCommits.js:119:57)
    at async fetchCommits (fetchCommits.js:142:9)
    at async HTMLAnchorElement.openCommitsTab (openCommitsTab.js:45:9)
```

**Comment by pprkut** [comment]
I just tested again (firefox reports version `1.0.51`) and now all the repos it failed with before are working :)
